### PR TITLE
Lineage pull request for: skeleton

### PR DESCRIPTION
**Pull request by cisagovbot**
# Lineage Pull Request #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-tf-module.git`](https://github.com/cisagov/skeleton-tf-module.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

---

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

### CODE REVIEW

**Review by dav3r — APPROVED** [review]

**Review by jsf9k — APPROVED** [review]

**Review by mcdonnnj — APPROVED** [review]
@dav3r Did you refresh the README contents using `terraform-docs` `v0.15.0`? I noticed some changes when checking locally that I do not see here.

**Comment by dav3r** [comment]
> @dav3r Did you refresh the README contents using `terraform-docs` `v0.15.0`? I noticed some changes when checking locally that I do not see here.

I did - what differences are you seeing?

**Comment by mcdonnnj** [comment]
> 
> 
> > @dav3r Did you refresh the README contents using `terraform-docs` `v0.15.0`? I noticed some changes when checking locally that I do not see here.
> 
> I did - what differences are you seeing?

Using

```console
$ terraform-docs markdown --anchor=false --html=false --lockfile=false .
```

and copying I see

```diff
--- a/README.md
+++ b/README.md
@@ -104,11 +104,11 @@ No modules.
 |------|-------------|------|---------|:--------:|
 | account\_ids | AWS account IDs that are allowed to assume the role. | `list(string)` | `[]` | no |
 | entity\_name | The name of the entity that the role is being created for (e.g. "test-user" or "host.example.com"). | `string` | n/a | yes |
-| iam\_usernames | The list of IAM usernames allowed to assume the role.  If not provided, defaults to allowing any user in the specified account(s).  Note that including "root" in this list will override any other usernames in the list. | `list(string)` | `["root"]` | no |
+| iam\_usernames | The list of IAM usernames allowed to assume the role.  If not provided, defaults to allowing any user in the specified account(s).  Note that including "root" in this list will override any other usernames in the list. | `list(string)` | ```[ "root" ]``` | no |
 | role\_description | The description to associate with the IAM role (as well as the corresponding policy) that allows read-only access to the specified SSM Parameter Store parameters.  Note that a "%s" in this value will get replaced with the entity\_name variable. | `string` | `"Allows read-only access to SSM Parameter Store parameters required for %s."` | no |
 | role\_name | The name to assign the IAM role (as well as the corresponding policy) that allows read-only access to the specified SSM Parameter Store parameters.  Note that a "%s" in this value will get replaced with the entity\_name variable. | `string` | `"ParameterStoreReadOnly-%s"` | no |
 | ssm\_names | A list of SSM Parameter Store parameters that the created role will be allowed to access. | `list(string)` | n/a | yes |
-| ssm\_regions | AWS regions of target SSMs (e.g. ["us-east-1", "us-east-2"]).  If not provided, defaults to all regions. | `list(string)` | `["*"]` | no |
+| ssm\_regions | AWS regions of target SSMs (e.g. ["us-east-1", "us-east-2"]).  If not provided, defaults to all regions. | `list(string)` | ```[ "*" ]``` | no |

 ## Outputs ##
 ```

If I've missed a flag or something please let me know.

**Comment by dav3r** [comment]
> > > @dav3r Did you refresh the README contents using `terraform-docs` `v0.15.0`? I noticed some changes when checking locally that I do not see here.
> > 
> > 
> > I did - what differences are you seeing?
> 
> Using
> 
> ```
> $ terraform-docs markdown --anchor=false --html=false --lockfile=false .
> ```

Ah, I haven't been using `--html=false`, but I will do that now.  I'll go back and double-check all of these PRs with that shortly.

**Review by jsf9k — APPROVED** [review]

**Review by jsf9k — APPROVED** [review]

**Review by mcdonnnj — APPROVED** [review]

**Pull request merged**
